#!/usr/bin/bash

dotdir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

link () {
  if [[ -L ~/.$1 ]]
  then
    return
  fi
  ln -s $dotdir/$1 ~/.$1
}

for file in *
do
  if [[ $file == "config" || $file == "install" ]]
  then
    continue
  fi
  link $file
done

for file in config/*
do
  link $file
done

